// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package lc

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockStarter creates a new instance of MockStarter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStarter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStarter {
	mock := &MockStarter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStarter is an autogenerated mock type for the Starter type
type MockStarter struct {
	mock.Mock
}

type MockStarter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStarter) EXPECT() *MockStarter_Expecter {
	return &MockStarter_Expecter{mock: &_m.Mock}
}

// Start provides a mock function for the type MockStarter
func (_mock *MockStarter) Start(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStarter_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockStarter_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStarter_Expecter) Start(ctx interface{}) *MockStarter_Start_Call {
	return &MockStarter_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockStarter_Start_Call) Run(run func(ctx context.Context)) *MockStarter_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStarter_Start_Call) Return(err error) *MockStarter_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStarter_Start_Call) RunAndReturn(run func(ctx context.Context) error) *MockStarter_Start_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStopper creates a new instance of MockStopper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStopper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStopper {
	mock := &MockStopper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStopper is an autogenerated mock type for the Stopper type
type MockStopper struct {
	mock.Mock
}

type MockStopper_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStopper) EXPECT() *MockStopper_Expecter {
	return &MockStopper_Expecter{mock: &_m.Mock}
}

// Stop provides a mock function for the type MockStopper
func (_mock *MockStopper) Stop(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStopper_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockStopper_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStopper_Expecter) Stop(ctx interface{}) *MockStopper_Stop_Call {
	return &MockStopper_Stop_Call{Call: _e.mock.On("Stop", ctx)}
}

func (_c *MockStopper_Stop_Call) Run(run func(ctx context.Context)) *MockStopper_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStopper_Stop_Call) Return(err error) *MockStopper_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStopper_Stop_Call) RunAndReturn(run func(ctx context.Context) error) *MockStopper_Stop_Call {
	_c.Call.Return(run)
	return _c
}
