package s3_test

import (
	s3sdk "github.com/aws/aws-sdk-go-v2/service/s3"
	"github.com/bronystylecrazy/ultrastructure/storage/s3"
)

var _ s3.Uploader = (*s3sdk.Client)(nil)
var _ s3.Downloader = (*s3sdk.Client)(nil)
var _ s3.MetadataGetter = (*s3sdk.Client)(nil)
var _ s3.Deleter = (*s3sdk.Client)(nil)
var _ s3.BatchDeleter = (*s3sdk.Client)(nil)
var _ s3.Copier = (*s3sdk.Client)(nil)
var _ s3.Lister = (*s3sdk.Client)(nil)
var _ s3.BucketLister = (*s3sdk.Client)(nil)
var _ s3.MultipartUploader = (*s3sdk.Client)(nil)
var _ s3.MultipartLister = (*s3sdk.Client)(nil)
var _ s3.BucketManager = (*s3sdk.Client)(nil)
var _ s3.AccessController = (*s3sdk.Client)(nil)
var _ s3.Tagger = (*s3sdk.Client)(nil)
var _ s3.PolicyManager = (*s3sdk.Client)(nil)
var _ s3.PublicAccessBlocker = (*s3sdk.Client)(nil)
var _ s3.Encryptor = (*s3sdk.Client)(nil)
var _ s3.LifecycleManager = (*s3sdk.Client)(nil)
var _ s3.Versioner = (*s3sdk.Client)(nil)
var _ s3.WebsiteManager = (*s3sdk.Client)(nil)
var _ s3.LoggingManager = (*s3sdk.Client)(nil)
var _ s3.NotificationManager = (*s3sdk.Client)(nil)
var _ s3.ReplicationManager = (*s3sdk.Client)(nil)
var _ s3.CORSManager = (*s3sdk.Client)(nil)
var _ s3.Accelerator = (*s3sdk.Client)(nil)
var _ s3.MetricsManager = (*s3sdk.Client)(nil)
var _ s3.AnalyticsManager = (*s3sdk.Client)(nil)
var _ s3.InventoryManager = (*s3sdk.Client)(nil)
var _ s3.IntelligentTieringManager = (*s3sdk.Client)(nil)
var _ s3.OwnershipManager = (*s3sdk.Client)(nil)
var _ s3.RequestPaymentManager = (*s3sdk.Client)(nil)
var _ s3.Locator = (*s3sdk.Client)(nil)
var _ s3.ObjectLockManager = (*s3sdk.Client)(nil)
var _ s3.LegalHoldManager = (*s3sdk.Client)(nil)
var _ s3.RetentionManager = (*s3sdk.Client)(nil)
var _ s3.Restorer = (*s3sdk.Client)(nil)
var _ s3.Selector = (*s3sdk.Client)(nil)
var _ s3.ObjectAttributesGetter = (*s3sdk.Client)(nil)
var _ s3.TorrentGetter = (*s3sdk.Client)(nil)
var _ s3.ObjectLambdaWriter = (*s3sdk.Client)(nil)
var _ s3.S3Manager = (*s3sdk.Client)(nil)

var _ s3.Presigner = (*s3sdk.PresignClient)(nil)
