package s3

import (
	s3sdk "github.com/aws/aws-sdk-go-v2/service/s3"
)

var _ Uploader = (*s3sdk.Client)(nil)
var _ Downloader = (*s3sdk.Client)(nil)
var _ MetadataGetter = (*s3sdk.Client)(nil)
var _ Deleter = (*s3sdk.Client)(nil)
var _ BatchDeleter = (*s3sdk.Client)(nil)
var _ Copier = (*s3sdk.Client)(nil)
var _ Lister = (*s3sdk.Client)(nil)
var _ BucketLister = (*s3sdk.Client)(nil)
var _ MultipartUploader = (*s3sdk.Client)(nil)
var _ MultipartLister = (*s3sdk.Client)(nil)
var _ BucketManager = (*s3sdk.Client)(nil)
var _ AccessController = (*s3sdk.Client)(nil)
var _ Tagger = (*s3sdk.Client)(nil)
var _ PolicyManager = (*s3sdk.Client)(nil)
var _ PublicAccessBlocker = (*s3sdk.Client)(nil)
var _ Encryptor = (*s3sdk.Client)(nil)
var _ LifecycleManager = (*s3sdk.Client)(nil)
var _ Versioner = (*s3sdk.Client)(nil)
var _ WebsiteManager = (*s3sdk.Client)(nil)
var _ LoggingManager = (*s3sdk.Client)(nil)
var _ NotificationManager = (*s3sdk.Client)(nil)
var _ ReplicationManager = (*s3sdk.Client)(nil)
var _ CORSManager = (*s3sdk.Client)(nil)
var _ Accelerator = (*s3sdk.Client)(nil)
var _ MetricsManager = (*s3sdk.Client)(nil)
var _ AnalyticsManager = (*s3sdk.Client)(nil)
var _ InventoryManager = (*s3sdk.Client)(nil)
var _ IntelligentTieringManager = (*s3sdk.Client)(nil)
var _ OwnershipManager = (*s3sdk.Client)(nil)
var _ RequestPaymentManager = (*s3sdk.Client)(nil)
var _ Locator = (*s3sdk.Client)(nil)
var _ ObjectLockManager = (*s3sdk.Client)(nil)
var _ LegalHoldManager = (*s3sdk.Client)(nil)
var _ RetentionManager = (*s3sdk.Client)(nil)
var _ Restorer = (*s3sdk.Client)(nil)
var _ Selector = (*s3sdk.Client)(nil)
var _ ObjectAttributesGetter = (*s3sdk.Client)(nil)
var _ TorrentGetter = (*s3sdk.Client)(nil)
var _ ObjectLambdaWriter = (*s3sdk.Client)(nil)
var _ S3Manager = (*s3sdk.Client)(nil)

var _ Presigner = (*s3sdk.PresignClient)(nil)
