// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package realtime

import (
	"github.com/gofiber/fiber/v3"
	"github.com/mochi-mqtt/server/v2"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthorizer creates a new instance of MockAuthorizer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthorizer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthorizer {
	mock := &MockAuthorizer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthorizer is an autogenerated mock type for the Authorizer type
type MockAuthorizer struct {
	mock.Mock
}

type MockAuthorizer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthorizer) EXPECT() *MockAuthorizer_Expecter {
	return &MockAuthorizer_Expecter{mock: &_m.Mock}
}

// Authorize provides a mock function for the type MockAuthorizer
func (_mock *MockAuthorizer) Authorize() fiber.Handler {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Authorize")
	}

	var r0 fiber.Handler
	if returnFunc, ok := ret.Get(0).(func() fiber.Handler); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(fiber.Handler)
		}
	}
	return r0
}

// MockAuthorizer_Authorize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authorize'
type MockAuthorizer_Authorize_Call struct {
	*mock.Call
}

// Authorize is a helper method to define mock.On call
func (_e *MockAuthorizer_Expecter) Authorize() *MockAuthorizer_Authorize_Call {
	return &MockAuthorizer_Authorize_Call{Call: _e.mock.On("Authorize")}
}

func (_c *MockAuthorizer_Authorize_Call) Run(run func()) *MockAuthorizer_Authorize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuthorizer_Authorize_Call) Return(v fiber.Handler) *MockAuthorizer_Authorize_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockAuthorizer_Authorize_Call) RunAndReturn(run func() fiber.Handler) *MockAuthorizer_Authorize_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBroker creates a new instance of MockBroker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBroker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBroker {
	mock := &MockBroker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBroker is an autogenerated mock type for the Broker type
type MockBroker struct {
	mock.Mock
}

type MockBroker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBroker) EXPECT() *MockBroker_Expecter {
	return &MockBroker_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function for the type MockBroker
func (_mock *MockBroker) Publish(topic string, payload []byte, retain bool, qos byte) error {
	ret := _mock.Called(topic, payload, retain, qos)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte, bool, byte) error); ok {
		r0 = returnFunc(topic, payload, retain, qos)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBroker_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockBroker_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - topic string
//   - payload []byte
//   - retain bool
//   - qos byte
func (_e *MockBroker_Expecter) Publish(topic interface{}, payload interface{}, retain interface{}, qos interface{}) *MockBroker_Publish_Call {
	return &MockBroker_Publish_Call{Call: _e.mock.On("Publish", topic, payload, retain, qos)}
}

func (_c *MockBroker_Publish_Call) Run(run func(topic string, payload []byte, retain bool, qos byte)) *MockBroker_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		var arg3 byte
		if args[3] != nil {
			arg3 = args[3].(byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBroker_Publish_Call) Return(err error) *MockBroker_Publish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBroker_Publish_Call) RunAndReturn(run func(topic string, payload []byte, retain bool, qos byte) error) *MockBroker_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// PublishJSON provides a mock function for the type MockBroker
func (_mock *MockBroker) PublishJSON(topic string, payload any, retain bool, qos byte) error {
	ret := _mock.Called(topic, payload, retain, qos)

	if len(ret) == 0 {
		panic("no return value specified for PublishJSON")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, any, bool, byte) error); ok {
		r0 = returnFunc(topic, payload, retain, qos)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBroker_PublishJSON_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishJSON'
type MockBroker_PublishJSON_Call struct {
	*mock.Call
}

// PublishJSON is a helper method to define mock.On call
//   - topic string
//   - payload any
//   - retain bool
//   - qos byte
func (_e *MockBroker_Expecter) PublishJSON(topic interface{}, payload interface{}, retain interface{}, qos interface{}) *MockBroker_PublishJSON_Call {
	return &MockBroker_PublishJSON_Call{Call: _e.mock.On("PublishJSON", topic, payload, retain, qos)}
}

func (_c *MockBroker_PublishJSON_Call) Run(run func(topic string, payload any, retain bool, qos byte)) *MockBroker_PublishJSON_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		var arg3 byte
		if args[3] != nil {
			arg3 = args[3].(byte)
		}
		run(arg0, arg1, arg2, arg3)
	})
	return _c
}

func (_c *MockBroker_PublishJSON_Call) Return(err error) *MockBroker_PublishJSON_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBroker_PublishJSON_Call) RunAndReturn(run func(topic string, payload any, retain bool, qos byte) error) *MockBroker_PublishJSON_Call {
	_c.Call.Return(run)
	return _c
}

// PublishString provides a mock function for the type MockBroker
func (_mock *MockBroker) PublishString(topic string, payload string, retain bool, qos byte) error {
	ret := _mock.Called(topic, payload, retain, qos)

	if len(ret) == 0 {
		panic("no return value specified for PublishString")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, bool, byte) error); ok {
		r0 = returnFunc(topic, payload, retain, qos)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBroker_PublishString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishString'
type MockBroker_PublishString_Call struct {
	*mock.Call
}

// PublishString is a helper method to define mock.On call
//   - topic string
//   - payload string
//   - retain bool
//   - qos byte
func (_e *MockBroker_Expecter) PublishString(topic interface{}, payload interface{}, retain interface{}, qos interface{}) *MockBroker_PublishString_Call {
	return &MockBroker_PublishString_Call{Call: _e.mock.On("PublishString", topic, payload, retain, qos)}
}

func (_c *MockBroker_PublishString_Call) Run(run func(topic string, payload string, retain bool, qos byte)) *MockBroker_PublishString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		var arg3 byte
		if args[3] != nil {
			arg3 = args[3].(byte)
		}
		run(arg0, arg1, arg2, arg3)
	})
	return _c
}

func (_c *MockBroker_PublishString_Call) Return(err error) *MockBroker_PublishString_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBroker_PublishString_Call) RunAndReturn(run func(topic string, payload string, retain bool, qos byte) error) *MockBroker_PublishString_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function for the type MockBroker
func (_mock *MockBroker) Subscribe(filter string, subscriptionId int, handler mqtt.InlineSubFn) error {
	ret := _mock.Called(filter, subscriptionId, handler)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, int, mqtt.InlineSubFn) error); ok {
		r0 = returnFunc(filter, subscriptionId, handler)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBroker_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockBroker_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - filter string
//   - subscriptionId int
//   - handler mqtt.InlineSubFn
func (_e *MockBroker_Expecter) Subscribe(filter interface{}, subscriptionId interface{}, handler interface{}) *MockBroker_Subscribe_Call {
	return &MockBroker_Subscribe_Call{Call: _e.mock.On("Subscribe", filter, subscriptionId, handler)}
}

func (_c *MockBroker_Subscribe_Call) Run(run func(filter string, subscriptionId int, handler mqtt.InlineSubFn)) *MockBroker_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 mqtt.InlineSubFn
		if args[2] != nil {
			arg2 = args[2].(mqtt.InlineSubFn)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBroker_Subscribe_Call) Return(err error) *MockBroker_Subscribe_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBroker_Subscribe_Call) RunAndReturn(run func(filter string, subscriptionId int, handler mqtt.InlineSubFn) error) *MockBroker_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// Unsubscribe provides a mock function for the type MockBroker
func (_mock *MockBroker) Unsubscribe(filter string, subscriptionId int) error {
	ret := _mock.Called(filter, subscriptionId)

	if len(ret) == 0 {
		panic("no return value specified for Unsubscribe")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, int) error); ok {
		r0 = returnFunc(filter, subscriptionId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBroker_Unsubscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unsubscribe'
type MockBroker_Unsubscribe_Call struct {
	*mock.Call
}

// Unsubscribe is a helper method to define mock.On call
//   - filter string
//   - subscriptionId int
func (_e *MockBroker_Expecter) Unsubscribe(filter interface{}, subscriptionId interface{}) *MockBroker_Unsubscribe_Call {
	return &MockBroker_Unsubscribe_Call{Call: _e.mock.On("Unsubscribe", filter, subscriptionId)}
}

func (_c *MockBroker_Unsubscribe_Call) Run(run func(filter string, subscriptionId int)) *MockBroker_Unsubscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBroker_Unsubscribe_Call) Return(err error) *MockBroker_Unsubscribe_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBroker_Unsubscribe_Call) RunAndReturn(run func(filter string, subscriptionId int) error) *MockBroker_Unsubscribe_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPublisher creates a new instance of MockPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPublisher {
	mock := &MockPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPublisher is an autogenerated mock type for the Publisher type
type MockPublisher struct {
	mock.Mock
}

type MockPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPublisher) EXPECT() *MockPublisher_Expecter {
	return &MockPublisher_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function for the type MockPublisher
func (_mock *MockPublisher) Publish(topic string, payload []byte, retain bool, qos byte) error {
	ret := _mock.Called(topic, payload, retain, qos)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte, bool, byte) error); ok {
		r0 = returnFunc(topic, payload, retain, qos)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPublisher_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockPublisher_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - topic string
//   - payload []byte
//   - retain bool
//   - qos byte
func (_e *MockPublisher_Expecter) Publish(topic interface{}, payload interface{}, retain interface{}, qos interface{}) *MockPublisher_Publish_Call {
	return &MockPublisher_Publish_Call{Call: _e.mock.On("Publish", topic, payload, retain, qos)}
}

func (_c *MockPublisher_Publish_Call) Run(run func(topic string, payload []byte, retain bool, qos byte)) *MockPublisher_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		var arg3 byte
		if args[3] != nil {
			arg3 = args[3].(byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPublisher_Publish_Call) Return(err error) *MockPublisher_Publish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPublisher_Publish_Call) RunAndReturn(run func(topic string, payload []byte, retain bool, qos byte) error) *MockPublisher_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// PublishJSON provides a mock function for the type MockPublisher
func (_mock *MockPublisher) PublishJSON(topic string, payload any, retain bool, qos byte) error {
	ret := _mock.Called(topic, payload, retain, qos)

	if len(ret) == 0 {
		panic("no return value specified for PublishJSON")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, any, bool, byte) error); ok {
		r0 = returnFunc(topic, payload, retain, qos)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPublisher_PublishJSON_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishJSON'
type MockPublisher_PublishJSON_Call struct {
	*mock.Call
}

// PublishJSON is a helper method to define mock.On call
//   - topic string
//   - payload any
//   - retain bool
//   - qos byte
func (_e *MockPublisher_Expecter) PublishJSON(topic interface{}, payload interface{}, retain interface{}, qos interface{}) *MockPublisher_PublishJSON_Call {
	return &MockPublisher_PublishJSON_Call{Call: _e.mock.On("PublishJSON", topic, payload, retain, qos)}
}

func (_c *MockPublisher_PublishJSON_Call) Run(run func(topic string, payload any, retain bool, qos byte)) *MockPublisher_PublishJSON_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		var arg3 byte
		if args[3] != nil {
			arg3 = args[3].(byte)
		}
		run(arg0, arg1, arg2, arg3)
	})
	return _c
}

func (_c *MockPublisher_PublishJSON_Call) Return(err error) *MockPublisher_PublishJSON_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPublisher_PublishJSON_Call) RunAndReturn(run func(topic string, payload any, retain bool, qos byte) error) *MockPublisher_PublishJSON_Call {
	_c.Call.Return(run)
	return _c
}

// PublishString provides a mock function for the type MockPublisher
func (_mock *MockPublisher) PublishString(topic string, payload string, retain bool, qos byte) error {
	ret := _mock.Called(topic, payload, retain, qos)

	if len(ret) == 0 {
		panic("no return value specified for PublishString")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, bool, byte) error); ok {
		r0 = returnFunc(topic, payload, retain, qos)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPublisher_PublishString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishString'
type MockPublisher_PublishString_Call struct {
	*mock.Call
}

// PublishString is a helper method to define mock.On call
//   - topic string
//   - payload string
//   - retain bool
//   - qos byte
func (_e *MockPublisher_Expecter) PublishString(topic interface{}, payload interface{}, retain interface{}, qos interface{}) *MockPublisher_PublishString_Call {
	return &MockPublisher_PublishString_Call{Call: _e.mock.On("PublishString", topic, payload, retain, qos)}
}

func (_c *MockPublisher_PublishString_Call) Run(run func(topic string, payload string, retain bool, qos byte)) *MockPublisher_PublishString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		var arg3 byte
		if args[3] != nil {
			arg3 = args[3].(byte)
		}
		run(arg0, arg1, arg2, arg3)
	})
	return _c
}

func (_c *MockPublisher_PublishString_Call) Return(err error) *MockPublisher_PublishString_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPublisher_PublishString_Call) RunAndReturn(run func(topic string, payload string, retain bool, qos byte) error) *MockPublisher_PublishString_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSubscriber creates a new instance of MockSubscriber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubscriber(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubscriber {
	mock := &MockSubscriber{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSubscriber is an autogenerated mock type for the Subscriber type
type MockSubscriber struct {
	mock.Mock
}

type MockSubscriber_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubscriber) EXPECT() *MockSubscriber_Expecter {
	return &MockSubscriber_Expecter{mock: &_m.Mock}
}

// Subscribe provides a mock function for the type MockSubscriber
func (_mock *MockSubscriber) Subscribe(filter string, subscriptionId int, handler mqtt.InlineSubFn) error {
	ret := _mock.Called(filter, subscriptionId, handler)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, int, mqtt.InlineSubFn) error); ok {
		r0 = returnFunc(filter, subscriptionId, handler)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSubscriber_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockSubscriber_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - filter string
//   - subscriptionId int
//   - handler mqtt.InlineSubFn
func (_e *MockSubscriber_Expecter) Subscribe(filter interface{}, subscriptionId interface{}, handler interface{}) *MockSubscriber_Subscribe_Call {
	return &MockSubscriber_Subscribe_Call{Call: _e.mock.On("Subscribe", filter, subscriptionId, handler)}
}

func (_c *MockSubscriber_Subscribe_Call) Run(run func(filter string, subscriptionId int, handler mqtt.InlineSubFn)) *MockSubscriber_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 mqtt.InlineSubFn
		if args[2] != nil {
			arg2 = args[2].(mqtt.InlineSubFn)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSubscriber_Subscribe_Call) Return(err error) *MockSubscriber_Subscribe_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSubscriber_Subscribe_Call) RunAndReturn(run func(filter string, subscriptionId int, handler mqtt.InlineSubFn) error) *MockSubscriber_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// Unsubscribe provides a mock function for the type MockSubscriber
func (_mock *MockSubscriber) Unsubscribe(filter string, subscriptionId int) error {
	ret := _mock.Called(filter, subscriptionId)

	if len(ret) == 0 {
		panic("no return value specified for Unsubscribe")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, int) error); ok {
		r0 = returnFunc(filter, subscriptionId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSubscriber_Unsubscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unsubscribe'
type MockSubscriber_Unsubscribe_Call struct {
	*mock.Call
}

// Unsubscribe is a helper method to define mock.On call
//   - filter string
//   - subscriptionId int
func (_e *MockSubscriber_Expecter) Unsubscribe(filter interface{}, subscriptionId interface{}) *MockSubscriber_Unsubscribe_Call {
	return &MockSubscriber_Unsubscribe_Call{Call: _e.mock.On("Unsubscribe", filter, subscriptionId)}
}

func (_c *MockSubscriber_Unsubscribe_Call) Run(run func(filter string, subscriptionId int)) *MockSubscriber_Unsubscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSubscriber_Unsubscribe_Call) Return(err error) *MockSubscriber_Unsubscribe_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSubscriber_Unsubscribe_Call) RunAndReturn(run func(filter string, subscriptionId int) error) *MockSubscriber_Unsubscribe_Call {
	_c.Call.Return(run)
	return _c
}
