// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package otel

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockObservable creates a new instance of MockObservable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockObservable(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockObservable {
	mock := &MockObservable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockObservable is an autogenerated mock type for the Observable type
type MockObservable struct {
	mock.Mock
}

type MockObservable_Expecter struct {
	mock *mock.Mock
}

func (_m *MockObservable) EXPECT() *MockObservable_Expecter {
	return &MockObservable_Expecter{mock: &_m.Mock}
}

// apply provides a mock function for the type MockObservable
func (_mock *MockObservable) apply(observer *Observer) {
	_mock.Called(observer)
	return
}

// MockObservable_apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'apply'
type MockObservable_apply_Call struct {
	*mock.Call
}

// apply is a helper method to define mock.On call
//   - observer *Observer
func (_e *MockObservable_Expecter) apply(observer interface{}) *MockObservable_apply_Call {
	return &MockObservable_apply_Call{Call: _e.mock.On("apply", observer)}
}

func (_c *MockObservable_apply_Call) Run(run func(observer *Observer)) *MockObservable_apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Observer
		if args[0] != nil {
			arg0 = args[0].(*Observer)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockObservable_apply_Call) Return() *MockObservable_apply_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockObservable_apply_Call) RunAndReturn(run func(observer *Observer)) *MockObservable_apply_Call {
	_c.Run(run)
	return _c
}
