// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package di

import (
	mock "github.com/stretchr/testify/mock"
	"go.uber.org/fx"
)

// NewMockNode creates a new instance of MockNode. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNode(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNode {
	mock := &MockNode{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNode is an autogenerated mock type for the Node type
type MockNode struct {
	mock.Mock
}

type MockNode_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNode) EXPECT() *MockNode_Expecter {
	return &MockNode_Expecter{mock: &_m.Mock}
}

// Build provides a mock function for the type MockNode
func (_mock *MockNode) Build() (fx.Option, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Build")
	}

	var r0 fx.Option
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (fx.Option, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() fx.Option); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(fx.Option)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNode_Build_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Build'
type MockNode_Build_Call struct {
	*mock.Call
}

// Build is a helper method to define mock.On call
func (_e *MockNode_Expecter) Build() *MockNode_Build_Call {
	return &MockNode_Build_Call{Call: _e.mock.On("Build")}
}

func (_c *MockNode_Build_Call) Run(run func()) *MockNode_Build_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNode_Build_Call) Return(option fx.Option, err error) *MockNode_Build_Call {
	_c.Call.Return(option, err)
	return _c
}

func (_c *MockNode_Build_Call) RunAndReturn(run func() (fx.Option, error)) *MockNode_Build_Call {
	_c.Call.Return(run)
	return _c
}

// newMockautoGroupApplier creates a new instance of mockautoGroupApplier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockautoGroupApplier(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockautoGroupApplier {
	mock := &mockautoGroupApplier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockautoGroupApplier is an autogenerated mock type for the autoGroupApplier type
type mockautoGroupApplier struct {
	mock.Mock
}

type mockautoGroupApplier_Expecter struct {
	mock *mock.Mock
}

func (_m *mockautoGroupApplier) EXPECT() *mockautoGroupApplier_Expecter {
	return &mockautoGroupApplier_Expecter{mock: &_m.Mock}
}

// withAutoGroups provides a mock function for the type mockautoGroupApplier
func (_mock *mockautoGroupApplier) withAutoGroups(autoGroupSetMoqParam autoGroupSet) Node {
	ret := _mock.Called(autoGroupSetMoqParam)

	if len(ret) == 0 {
		panic("no return value specified for withAutoGroups")
	}

	var r0 Node
	if returnFunc, ok := ret.Get(0).(func(autoGroupSet) Node); ok {
		r0 = returnFunc(autoGroupSetMoqParam)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Node)
		}
	}
	return r0
}

// mockautoGroupApplier_withAutoGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'withAutoGroups'
type mockautoGroupApplier_withAutoGroups_Call struct {
	*mock.Call
}

// withAutoGroups is a helper method to define mock.On call
//   - autoGroupSetMoqParam autoGroupSet
func (_e *mockautoGroupApplier_Expecter) withAutoGroups(autoGroupSetMoqParam interface{}) *mockautoGroupApplier_withAutoGroups_Call {
	return &mockautoGroupApplier_withAutoGroups_Call{Call: _e.mock.On("withAutoGroups", autoGroupSetMoqParam)}
}

func (_c *mockautoGroupApplier_withAutoGroups_Call) Run(run func(autoGroupSetMoqParam autoGroupSet)) *mockautoGroupApplier_withAutoGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 autoGroupSet
		if args[0] != nil {
			arg0 = args[0].(autoGroupSet)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockautoGroupApplier_withAutoGroups_Call) Return(node Node) *mockautoGroupApplier_withAutoGroups_Call {
	_c.Call.Return(node)
	return _c
}

func (_c *mockautoGroupApplier_withAutoGroups_Call) RunAndReturn(run func(autoGroupSetMoqParam autoGroupSet) Node) *mockautoGroupApplier_withAutoGroups_Call {
	_c.Call.Return(run)
	return _c
}

// newMockautoInjectApplier creates a new instance of mockautoInjectApplier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockautoInjectApplier(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockautoInjectApplier {
	mock := &mockautoInjectApplier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockautoInjectApplier is an autogenerated mock type for the autoInjectApplier type
type mockautoInjectApplier struct {
	mock.Mock
}

type mockautoInjectApplier_Expecter struct {
	mock *mock.Mock
}

func (_m *mockautoInjectApplier) EXPECT() *mockautoInjectApplier_Expecter {
	return &mockautoInjectApplier_Expecter{mock: &_m.Mock}
}

// withAutoInjectFields provides a mock function for the type mockautoInjectApplier
func (_mock *mockautoInjectApplier) withAutoInjectFields(b bool) Node {
	ret := _mock.Called(b)

	if len(ret) == 0 {
		panic("no return value specified for withAutoInjectFields")
	}

	var r0 Node
	if returnFunc, ok := ret.Get(0).(func(bool) Node); ok {
		r0 = returnFunc(b)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Node)
		}
	}
	return r0
}

// mockautoInjectApplier_withAutoInjectFields_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'withAutoInjectFields'
type mockautoInjectApplier_withAutoInjectFields_Call struct {
	*mock.Call
}

// withAutoInjectFields is a helper method to define mock.On call
//   - b bool
func (_e *mockautoInjectApplier_Expecter) withAutoInjectFields(b interface{}) *mockautoInjectApplier_withAutoInjectFields_Call {
	return &mockautoInjectApplier_withAutoInjectFields_Call{Call: _e.mock.On("withAutoInjectFields", b)}
}

func (_c *mockautoInjectApplier_withAutoInjectFields_Call) Run(run func(b bool)) *mockautoInjectApplier_withAutoInjectFields_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockautoInjectApplier_withAutoInjectFields_Call) Return(node Node) *mockautoInjectApplier_withAutoInjectFields_Call {
	_c.Call.Return(node)
	return _c
}

func (_c *mockautoInjectApplier_withAutoInjectFields_Call) RunAndReturn(run func(b bool) Node) *mockautoInjectApplier_withAutoInjectFields_Call {
	_c.Call.Return(run)
	return _c
}

// newMockerrorWithGraph creates a new instance of mockerrorWithGraph. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockerrorWithGraph(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockerrorWithGraph {
	mock := &mockerrorWithGraph{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockerrorWithGraph is an autogenerated mock type for the errorWithGraph type
type mockerrorWithGraph struct {
	mock.Mock
}

type mockerrorWithGraph_Expecter struct {
	mock *mock.Mock
}

func (_m *mockerrorWithGraph) EXPECT() *mockerrorWithGraph_Expecter {
	return &mockerrorWithGraph_Expecter{mock: &_m.Mock}
}

// Graph provides a mock function for the type mockerrorWithGraph
func (_mock *mockerrorWithGraph) Graph() fx.DotGraph {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Graph")
	}

	var r0 fx.DotGraph
	if returnFunc, ok := ret.Get(0).(func() fx.DotGraph); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(fx.DotGraph)
	}
	return r0
}

// mockerrorWithGraph_Graph_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Graph'
type mockerrorWithGraph_Graph_Call struct {
	*mock.Call
}

// Graph is a helper method to define mock.On call
func (_e *mockerrorWithGraph_Expecter) Graph() *mockerrorWithGraph_Graph_Call {
	return &mockerrorWithGraph_Graph_Call{Call: _e.mock.On("Graph")}
}

func (_c *mockerrorWithGraph_Graph_Call) Run(run func()) *mockerrorWithGraph_Graph_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockerrorWithGraph_Graph_Call) Return(dotGraph fx.DotGraph) *mockerrorWithGraph_Graph_Call {
	_c.Call.Return(dotGraph)
	return _c
}

func (_c *mockerrorWithGraph_Graph_Call) RunAndReturn(run func() fx.DotGraph) *mockerrorWithGraph_Graph_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOption creates a new instance of MockOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOption {
	mock := &MockOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOption is an autogenerated mock type for the Option type
type MockOption struct {
	mock.Mock
}

type MockOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOption) EXPECT() *MockOption_Expecter {
	return &MockOption_Expecter{mock: &_m.Mock}
}

// applyBind provides a mock function for the type MockOption
func (_mock *MockOption) applyBind(bindConfigMoqParam *bindConfig) {
	_mock.Called(bindConfigMoqParam)
	return
}

// MockOption_applyBind_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'applyBind'
type MockOption_applyBind_Call struct {
	*mock.Call
}

// applyBind is a helper method to define mock.On call
//   - bindConfigMoqParam *bindConfig
func (_e *MockOption_Expecter) applyBind(bindConfigMoqParam interface{}) *MockOption_applyBind_Call {
	return &MockOption_applyBind_Call{Call: _e.mock.On("applyBind", bindConfigMoqParam)}
}

func (_c *MockOption_applyBind_Call) Run(run func(bindConfigMoqParam *bindConfig)) *MockOption_applyBind_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *bindConfig
		if args[0] != nil {
			arg0 = args[0].(*bindConfig)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOption_applyBind_Call) Return() *MockOption_applyBind_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockOption_applyBind_Call) RunAndReturn(run func(bindConfigMoqParam *bindConfig)) *MockOption_applyBind_Call {
	_c.Run(run)
	return _c
}

// applyParam provides a mock function for the type MockOption
func (_mock *MockOption) applyParam(paramConfigMoqParam *paramConfig) {
	_mock.Called(paramConfigMoqParam)
	return
}

// MockOption_applyParam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'applyParam'
type MockOption_applyParam_Call struct {
	*mock.Call
}

// applyParam is a helper method to define mock.On call
//   - paramConfigMoqParam *paramConfig
func (_e *MockOption_Expecter) applyParam(paramConfigMoqParam interface{}) *MockOption_applyParam_Call {
	return &MockOption_applyParam_Call{Call: _e.mock.On("applyParam", paramConfigMoqParam)}
}

func (_c *MockOption_applyParam_Call) Run(run func(paramConfigMoqParam *paramConfig)) *MockOption_applyParam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *paramConfig
		if args[0] != nil {
			arg0 = args[0].(*paramConfig)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOption_applyParam_Call) Return() *MockOption_applyParam_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockOption_applyParam_Call) RunAndReturn(run func(paramConfigMoqParam *paramConfig)) *MockOption_applyParam_Call {
	_c.Run(run)
	return _c
}

// NewMockNodeOption creates a new instance of MockNodeOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNodeOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNodeOption {
	mock := &MockNodeOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNodeOption is an autogenerated mock type for the NodeOption type
type MockNodeOption struct {
	mock.Mock
}

type MockNodeOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNodeOption) EXPECT() *MockNodeOption_Expecter {
	return &MockNodeOption_Expecter{mock: &_m.Mock}
}

// Build provides a mock function for the type MockNodeOption
func (_mock *MockNodeOption) Build() (fx.Option, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Build")
	}

	var r0 fx.Option
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (fx.Option, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() fx.Option); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(fx.Option)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNodeOption_Build_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Build'
type MockNodeOption_Build_Call struct {
	*mock.Call
}

// Build is a helper method to define mock.On call
func (_e *MockNodeOption_Expecter) Build() *MockNodeOption_Build_Call {
	return &MockNodeOption_Build_Call{Call: _e.mock.On("Build")}
}

func (_c *MockNodeOption_Build_Call) Run(run func()) *MockNodeOption_Build_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNodeOption_Build_Call) Return(option fx.Option, err error) *MockNodeOption_Build_Call {
	_c.Call.Return(option, err)
	return _c
}

func (_c *MockNodeOption_Build_Call) RunAndReturn(run func() (fx.Option, error)) *MockNodeOption_Build_Call {
	_c.Call.Return(run)
	return _c
}

// applyBind provides a mock function for the type MockNodeOption
func (_mock *MockNodeOption) applyBind(bindConfigMoqParam *bindConfig) {
	_mock.Called(bindConfigMoqParam)
	return
}

// MockNodeOption_applyBind_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'applyBind'
type MockNodeOption_applyBind_Call struct {
	*mock.Call
}

// applyBind is a helper method to define mock.On call
//   - bindConfigMoqParam *bindConfig
func (_e *MockNodeOption_Expecter) applyBind(bindConfigMoqParam interface{}) *MockNodeOption_applyBind_Call {
	return &MockNodeOption_applyBind_Call{Call: _e.mock.On("applyBind", bindConfigMoqParam)}
}

func (_c *MockNodeOption_applyBind_Call) Run(run func(bindConfigMoqParam *bindConfig)) *MockNodeOption_applyBind_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *bindConfig
		if args[0] != nil {
			arg0 = args[0].(*bindConfig)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNodeOption_applyBind_Call) Return() *MockNodeOption_applyBind_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNodeOption_applyBind_Call) RunAndReturn(run func(bindConfigMoqParam *bindConfig)) *MockNodeOption_applyBind_Call {
	_c.Run(run)
	return _c
}

// applyParam provides a mock function for the type MockNodeOption
func (_mock *MockNodeOption) applyParam(paramConfigMoqParam *paramConfig) {
	_mock.Called(paramConfigMoqParam)
	return
}

// MockNodeOption_applyParam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'applyParam'
type MockNodeOption_applyParam_Call struct {
	*mock.Call
}

// applyParam is a helper method to define mock.On call
//   - paramConfigMoqParam *paramConfig
func (_e *MockNodeOption_Expecter) applyParam(paramConfigMoqParam interface{}) *MockNodeOption_applyParam_Call {
	return &MockNodeOption_applyParam_Call{Call: _e.mock.On("applyParam", paramConfigMoqParam)}
}

func (_c *MockNodeOption_applyParam_Call) Run(run func(paramConfigMoqParam *paramConfig)) *MockNodeOption_applyParam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *paramConfig
		if args[0] != nil {
			arg0 = args[0].(*paramConfig)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNodeOption_applyParam_Call) Return() *MockNodeOption_applyParam_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNodeOption_applyParam_Call) RunAndReturn(run func(paramConfigMoqParam *paramConfig)) *MockNodeOption_applyParam_Call {
	_c.Run(run)
	return _c
}
