//go:build !autoswag_analyze
// +build !autoswag_analyze

// Code generated by Ultrastructure AutoSwag vdevel; DO NOT EDIT.

package main

import (
	autoswag "github.com/bronystylecrazy/ultrastructure/x/autoswag"
	dm "github.com/bronystylecrazy/ultrastructure/examples/web-basic/src/app/dm"
	fiber "github.com/gofiber/fiber/v3"
	http "net/http"
	multipart "mime/multipart"
	"strings"
	web "github.com/bronystylecrazy/ultrastructure/web"
)

func AutoSwagGenerator(ctx *autoswag.Context) {
	if ctx == nil {
		return
	}
	path := strings.TrimSpace(ctx.Path)
	if path == "" {
		path = "/"
	}
	if len(path) > 1 {
		path = strings.TrimRight(path, "/")
	}
	routeKey := ctx.Method + " " + path
	switch routeKey {
	case "GET /api/v1":
		ctx.SetRequestBody(ExampleForm{}, true, fiber.MIMEApplicationJSON)
		ctx.SetResponseAs(http.StatusOK, struct{Name string; Age int; Avatar *multipart.FileHeader}{}, fiber.MIMEApplicationJSON, "Auto-detected")
		return
	case "GET /api/v1/haha":
		ctx.SetQuery(ExampleQueryHaha{})
		ctx.SetResponseAs(http.StatusOK, struct{Name string; Age int; Avatar *multipart.FileHeader}{}, fiber.MIMEApplicationJSON, "Auto-detected")
		return
	case "GET /api/v1/dm":
		ctx.SetResponseAs(http.StatusOK, "", fiber.MIMETextPlain, "This is example command for c.SendString(\"Hello, World!\")")
		return
	case "GET /api/v1/gm/{id}":
		ctx.SetQuery(dm.ExampleQueryHaha{})
		ctx.AddModelFieldDescription(dm.ExampleQueryHaha{}, "Name", "this is example for sirawit")
		ctx.SetResponseAs(http.StatusOK, dm.Response{}, fiber.MIMEApplicationJSON, "Auto-detected")
		return
	case "GET /dm/{id}":
		ctx.SetResponseAs(http.StatusOK, struct{ID string "json:\"id__id\""; Text string "json:\"text__textss\""}{}, fiber.MIMEApplicationJSON, "Auto-detected")
		ctx.SetResponseAs(http.StatusOK, struct{ID string "json:\"id__id\""; Text string "json:\"text__textss___eie\""}{}, fiber.MIMEApplicationJSON, "This is example command, ei ei, for example sdjfksdjf hahaha")
		return
	case "GET /api/v1/px":
		ctx.AddTag("PeopleExperience")
		ctx.AddTagDescription("PeopleExperience", "this is example for Sirawit")
		ctx.SetResponseAs(http.StatusOK, "", fiber.MIMETextPlain, "hello world")
		return
	case "GET /api/v1/px/description", "GET /api/v1/px/healthz", "GET /api/v1/px/users/{id_or_uuid}/pooler":
		ctx.AddTag("PeopleExperience")
		ctx.AddTagDescription("PeopleExperience", "this is example for Sirawit")
		ctx.SetResponseAs(http.StatusOK, "", fiber.MIMETextPlain, "Auto-detected")
		return
	case "GET /api/v1/px/health":
		ctx.AddTag("PeopleExperience")
		ctx.AddTagDescription("PeopleExperience", "this is example for Sirawit")
		ctx.SetResponseAs(http.StatusOK, struct{IHereThundie string "json:\"i_here_thundie\" description:\"i'm here thundie\""}{}, fiber.MIMEApplicationJSON, "this is example for Hello World")
		ctx.SetResponseAs(http.StatusCreated, web.Response{}, fiber.MIMEApplicationJSON, "this is example for Sirawit")
		return
	default:
		return
	}
}
