// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package license

import (
	"github.com/golang-jwt/jwt/v5"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEncodeDecoder creates a new instance of MockEncodeDecoder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEncodeDecoder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEncodeDecoder {
	mock := &MockEncodeDecoder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEncodeDecoder is an autogenerated mock type for the EncodeDecoder type
type MockEncodeDecoder struct {
	mock.Mock
}

type MockEncodeDecoder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEncodeDecoder) EXPECT() *MockEncodeDecoder_Expecter {
	return &MockEncodeDecoder_Expecter{mock: &_m.Mock}
}

// Decode provides a mock function for the type MockEncodeDecoder
func (_mock *MockEncodeDecoder) Decode(token string) (jwt.MapClaims, error) {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Decode")
	}

	var r0 jwt.MapClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (jwt.MapClaims, error)); ok {
		return returnFunc(token)
	}
	if returnFunc, ok := ret.Get(0).(func(string) jwt.MapClaims); ok {
		r0 = returnFunc(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jwt.MapClaims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEncodeDecoder_Decode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decode'
type MockEncodeDecoder_Decode_Call struct {
	*mock.Call
}

// Decode is a helper method to define mock.On call
//   - token string
func (_e *MockEncodeDecoder_Expecter) Decode(token interface{}) *MockEncodeDecoder_Decode_Call {
	return &MockEncodeDecoder_Decode_Call{Call: _e.mock.On("Decode", token)}
}

func (_c *MockEncodeDecoder_Decode_Call) Run(run func(token string)) *MockEncodeDecoder_Decode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEncodeDecoder_Decode_Call) Return(mapClaims jwt.MapClaims, err error) *MockEncodeDecoder_Decode_Call {
	_c.Call.Return(mapClaims, err)
	return _c
}

func (_c *MockEncodeDecoder_Decode_Call) RunAndReturn(run func(token string) (jwt.MapClaims, error)) *MockEncodeDecoder_Decode_Call {
	_c.Call.Return(run)
	return _c
}

// Encode provides a mock function for the type MockEncodeDecoder
func (_mock *MockEncodeDecoder) Encode(claims *jwt.MapClaims) (string, error) {
	ret := _mock.Called(claims)

	if len(ret) == 0 {
		panic("no return value specified for Encode")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*jwt.MapClaims) (string, error)); ok {
		return returnFunc(claims)
	}
	if returnFunc, ok := ret.Get(0).(func(*jwt.MapClaims) string); ok {
		r0 = returnFunc(claims)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(*jwt.MapClaims) error); ok {
		r1 = returnFunc(claims)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEncodeDecoder_Encode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encode'
type MockEncodeDecoder_Encode_Call struct {
	*mock.Call
}

// Encode is a helper method to define mock.On call
//   - claims *jwt.MapClaims
func (_e *MockEncodeDecoder_Expecter) Encode(claims interface{}) *MockEncodeDecoder_Encode_Call {
	return &MockEncodeDecoder_Encode_Call{Call: _e.mock.On("Encode", claims)}
}

func (_c *MockEncodeDecoder_Encode_Call) Run(run func(claims *jwt.MapClaims)) *MockEncodeDecoder_Encode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *jwt.MapClaims
		if args[0] != nil {
			arg0 = args[0].(*jwt.MapClaims)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEncodeDecoder_Encode_Call) Return(s string, err error) *MockEncodeDecoder_Encode_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockEncodeDecoder_Encode_Call) RunAndReturn(run func(claims *jwt.MapClaims) (string, error)) *MockEncodeDecoder_Encode_Call {
	_c.Call.Return(run)
	return _c
}
