// Code generated by Signr. DO NOT EDIT.
// Exported public keys for offline verification.

package license

// PublicKeys maps key IDs to base64url-encoded Ed25519 public keys.
var PublicKeys = map[string]string{
	// will be generated during CI/CD
}
