package web

// Common HTTP media type constants for request/response content negotiation.
const (
	ContentTypeApplicationJSON                = "application/json"
	ContentTypeApplicationXML                 = "application/xml"
	ContentTypeApplicationYAML                = "application/yaml"
	ContentTypeApplicationXWWWFormURLEncoded  = "application/x-www-form-urlencoded"
	ContentTypeApplicationOctetStream         = "application/octet-stream"
	ContentTypeApplicationPDF                 = "application/pdf"
	ContentTypeApplicationZIP                 = "application/zip"
	ContentTypeApplicationGZIP                = "application/gzip"
	ContentTypeApplicationMsgpack             = "application/msgpack"
	ContentTypeApplicationProtobuf            = "application/protobuf"
	ContentTypeApplicationJavaScript          = "application/javascript"
	ContentTypeApplicationLDJSON              = "application/ld+json"
	ContentTypeApplicationNDJSON              = "application/x-ndjson"
	ContentTypeApplicationProblemJSON         = "application/problem+json"
	ContentTypeApplicationProblemXML          = "application/problem+xml"
	ContentTypeApplicationGraphQL             = "application/graphql"
	ContentTypeApplicationGraphQLResponseJSON = "application/graphql-response+json"
	ContentTypeApplicationWASM                = "application/wasm"
	ContentTypeMultipartFormData              = "multipart/form-data"
	ContentTypeMultipartMixed                 = "multipart/mixed"
	ContentTypeMultipartAlternative           = "multipart/alternative"
	ContentTypeTextPlain                      = "text/plain"
	ContentTypeTextHTML                       = "text/html"
	ContentTypeTextCSS                        = "text/css"
	ContentTypeTextCSV                        = "text/csv"
	ContentTypeTextXML                        = "text/xml"
	ContentTypeTextJavaScript                 = "text/javascript"
	ContentTypeTextMarkdown                   = "text/markdown"
	ContentTypeTextCalendar                   = "text/calendar"
	ContentTypeTextEventStream                = "text/event-stream"
	ContentTypeImagePNG                       = "image/png"
	ContentTypeImageJPEG                      = "image/jpeg"
	ContentTypeImageGIF                       = "image/gif"
	ContentTypeImageWEBP                      = "image/webp"
	ContentTypeImageSVGXML                    = "image/svg+xml"
	ContentTypeImageICO                       = "image/x-icon"
	ContentTypeAudioMPEG                      = "audio/mpeg"
	ContentTypeAudioWAV                       = "audio/wav"
	ContentTypeAudioOGG                       = "audio/ogg"
	ContentTypeVideoMP4                       = "video/mp4"
	ContentTypeVideoWEBM                      = "video/webm"
	ContentTypeVideoOGG                       = "video/ogg"
	ContentTypeFontWOFF                       = "font/woff"
	ContentTypeFontWOFF2                      = "font/woff2"
	ContentTypeFontTTF                        = "font/ttf"
	ContentTypeFontOTF                        = "font/otf"
)
