// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package web

import (
	"github.com/gofiber/fiber/v3"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHandler creates a new instance of MockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandler {
	mock := &MockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHandler is an autogenerated mock type for the Handler type
type MockHandler struct {
	mock.Mock
}

type MockHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHandler) EXPECT() *MockHandler_Expecter {
	return &MockHandler_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function for the type MockHandler
func (_mock *MockHandler) Handle(r fiber.Router) {
	_mock.Called(r)
	return
}

// MockHandler_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MockHandler_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - r fiber.Router
func (_e *MockHandler_Expecter) Handle(r interface{}) *MockHandler_Handle_Call {
	return &MockHandler_Handle_Call{Call: _e.mock.On("Handle", r)}
}

func (_c *MockHandler_Handle_Call) Run(run func(r fiber.Router)) *MockHandler_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 fiber.Router
		if args[0] != nil {
			arg0 = args[0].(fiber.Router)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHandler_Handle_Call) Return() *MockHandler_Handle_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHandler_Handle_Call) RunAndReturn(run func(r fiber.Router)) *MockHandler_Handle_Call {
	_c.Run(run)
	return _c
}
